#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# CONFIGURE DATA DIRECTORY
#=================================================
ynh_script_progression "Configuring a data directory..."

ynh_restore "$data_dir/"

chown -R "$app:www-data" "$data_dir"


#================================================
# RESTORE THE PostgreSQL DATABASE
#=================================================
ynh_script_progression "Restoring the PostgreSQL database..."

ynh_psql_db_shell < ./db.sql

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

### nginx 
ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

### service file
ynh_restore "/etc/systemd/system/$app.service"

systemctl enable "$app.service" --quiet
yunohost service add "$app" --description="Saltcorn No-Code Editor" --log="/var/log/$app/$app.log"

mkdir -p "/var/log/$app"
ynh_restore "/etc/logrotate.d/$app"
touch /var/log/$app/$app.log
chown -R $app:$app /var/log/$app/

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app" --action="start"

ynh_systemctl --service=nginx --action="reload"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
